/*
 * Copyright 2012  Samsung Electronics Co., Ltd
 *
 * Licensed under the Flora License, Version 1.0 (the License);
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.tizenopensource.org/license
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */



#ifdef KEY_CONFIGURE_PHASE
{
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},

	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},

	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CONTROL, POPUP_TYPE_NONE, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CHAR, POPUP_TYPE_AUTO_POPUP, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CONTROL, POPUP_TYPE_NONE, TRUE, TRUE, TRUE, {NOT_USED,}},

	/*option*/	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_MODECHANGE, POPUP_TYPE_CONTEXT_POPUP, FALSE, FALSE, TRUE, {NOT_USED,}},
	/*abc*/{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_MODECHANGE, POPUP_TYPE_BTN_LONGPRESS_POPUP_ONCE, FALSE, FALSE, TRUE, {INPUT_MODE_EMOTICON_POPUP, NOT_USED, NOT_USED, NOT_USED, NOT_USED, NOT_USED, NOT_USED}},
	/* Default SubLayout */
	// {
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CONTROL, POPUP_TYPE_NONE, FALSE, FALSE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_DIRECTION, KEY_TYPE_UNICODE, POPUP_TYPE_BTN_LONGPRESS_POPUP_ONCE, FALSE, FALSE, TRUE, {INPUT_MODE_PUNCTUATION_POPUP, NOT_USED, NOT_USED, NOT_USED, NOT_USED, NOT_USED, NOT_USED}},
	// }
	/* WithVoice SubLayout */
	// {
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CONTROL, POPUP_TYPE_BTN_RELEASE_POPUP_ONCE, FALSE, FALSE, TRUE, {INPUT_MODE_SCENETEXT_POPUP, NOT_USED, NOT_USED, NOT_USED, NOT_USED, NOT_USED, NOT_USED}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CONTROL, POPUP_TYPE_NONE, FALSE, FALSE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_DIRECTION, KEY_TYPE_UNICODE, POPUP_TYPE_BTN_LONGPRESS_POPUP_ONCE, FALSE, FALSE, TRUE, {INPUT_MODE_PUNCTUATION_POPUP, NOT_USED, NOT_USED, NOT_USED, NOT_USED, NOT_USED, NOT_USED}},
	// }
	/* URL SubLayout */
	// {
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CONTROL, POPUP_TYPE_NONE, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_UNICODE, POPUP_TYPE_NONE, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, CUSTOMID_WWWCOM, BUTTON_TYPE_NORMAL, KEY_TYPE_UNICODE, POPUP_TYPE_BTN_LONGPRESS_POPUP_ONCE, TRUE, TRUE, TRUE, {INPUT_MODE_URL_POPUP, NOT_USED, NOT_USED, NOT_USED, NOT_USED, NOT_USED, NOT_USED}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_UNICODE, POPUP_TYPE_NONE, TRUE, TRUE, TRUE, {NOT_USED,}},
	// }
	/* Email SubLayout */
	// {
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_CONTROL, POPUP_TYPE_NONE, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_UNICODE, POPUP_TYPE_NONE, TRUE, TRUE, TRUE, {NOT_USED,}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_UNICODE, POPUP_TYPE_BTN_LONGPRESS_POPUP_ONCE, TRUE, TRUE, TRUE, {INPUT_MODE_URL_POPUP, NOT_USED, NOT_USED, NOT_USED, NOT_USED, NOT_USED, NOT_USED}},
	{USED, NOT_USED, BUTTON_TYPE_NORMAL, KEY_TYPE_UNICODE, POPUP_TYPE_NONE, TRUE, TRUE, TRUE, {NOT_USED,}},
	// }
	/*enter*/{USED, CUSTOMID_ENTER, BUTTON_TYPE_NORMAL, KEY_TYPE_CONTROL, POPUP_TYPE_NONE, FALSE, FALSE, TRUE, {NOT_USED,}},

	{NOT_USED,},
}
#endif


#ifdef KEY_PROPERTIES_PHASE
{
		/* fValid, labelCnt, label, labelPropId, imgPath, keyValueCnt, keyValue, keyEvent, longKeyValue, longKeyEvent, userLabel,  userKeyValue,  userKeyEvent, */
	{
		USED, /* 1x1 042F 044F*/
		2,
		_Label_ {{"\xd1\x8f"},{"\xd0\xaf"},{"\xd0\xaf"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		2,
		_KeyVal_ {{"\xd1\x8f"},{"\xd0\xaf"},{"\xd0\xaf"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_YA},{MVK_RUSSIAN_CAPITAL_YA},{MVK_RUSSIAN_CAPITAL_YA}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 1x2 0436 0416*/
		2,
		_Label_ {{"\xd0\xb6"},{"\xd0\x96"},{"\xd0\x96"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		2,
		_KeyVal_{{"\xd0\xb6"},{"\xd0\x96"},{"\xd0\x96"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_ZHE},{MVK_RUSSIAN_CAPITAL_ZHE},{MVK_RUSSIAN_CAPITAL_ZHE}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 1x3 0435 0415*/
		2,
		_Label_ {{"\xd0\xb5"},{"\xd0\x95"},{"\xd0\x95"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		2,
		_KeyVal_ {{"\xd0\xb5"},{"\xd0\x95"},{"\xd0\x95"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_IE},{MVK_RUSSIAN_CAPITAL_IE},{MVK_RUSSIAN_CAPITAL_IE}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 1x4 0440 0420*/
		1,
		_Label_ {{"\xd1\x80"},{"\xd0\xa0"},{"\xd0\xa0"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		1,
		_KeyVal_ {{"\xd1\x80"},{"\xd0\xa0"},{"\xd0\xa0"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_ER},{MVK_RUSSIAN_CAPITAL_ER},{MVK_RUSSIAN_CAPITAL_ER}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 1x5 0442 0422*/
		2,
		_Label_ {{"\xd1\x82"},{"\xd0\xa2"},{"\xd0\xa2"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		1,
		_KeyVal_ {{"\xd1\x82"},{"\xd0\xa2"},{"\xd0\xa2"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_TE},{MVK_RUSSIAN_CAPITAL_TE},{MVK_RUSSIAN_CAPITAL_TE}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 1x6 044B 042B*/
		2,
		_Label_ {{"\xd1\x8b"},{"\xd0\xab"},{"\xd0\xab"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		2,
		_KeyVal_ {{"\xd1\x8b"},{"\xd0\xab"},{"\xd0\xab"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_YERU},{MVK_RUSSIAN_CAPITAL_YERU},{MVK_RUSSIAN_CAPITAL_YERU}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 1x7 0443 0423*/
		2,
		_Label_ {{"\xd1\x83"},{"\xd0\xa3"},{"\xd0\xa3"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		2,
		_KeyVal_ {{"\xd1\x83"},{"\xd0\xa3"},{"\xd0\xa3"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_U},{MVK_RUSSIAN_CAPITAL_U},{MVK_RUSSIAN_CAPITAL_U}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 1x8 0438 0418*/
		2,
		_Label_ {{"\xd0\xb8"},{"\xd0\x98"},{"\xd0\x98"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		2,
		_KeyVal_ {{"\xd0\xb8"},{"\xd0\x98"},{"\xd0\x98"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_I},{MVK_RUSSIAN_CAPITAL_I},{MVK_RUSSIAN_CAPITAL_I}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 1x9 043E 041E*/
		2,
		_Label_ {{"\xd0\xbe"},{"\xd0\x9e"},{"\xd0\x9e"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		2,
		_KeyVal_ {{"\xd0\xbe"},{"\xd0\x9e"},{"\xd0\x9e"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_O},{MVK_RUSSIAN_CAPITAL_O},{MVK_RUSSIAN_CAPITAL_O}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 1x10 043F 041F*/
		2,
		_Label_ {{"\xd0\xbf"},{"\xd0\x9f"},{"\xd0\x9f"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		2,
		_KeyVal_ {{"\xd0\xbf"},{"\xd0\x9f"},{"\xd0\x9f"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_PE},{MVK_RUSSIAN_CAPITAL_PE},{MVK_RUSSIAN_CAPITAL_PE}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 1x11 0448 0428*/
		2,
		_Label_ {{"\xd1\x88"},{"\xd0\xa8"},{"\xd0\xa8"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		2,
		_KeyVal_ {{"\xd1\x88"},{"\xd0\xa8"},{"\xd0\xa8"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_SHA},{MVK_RUSSIAN_CAPITAL_SHA},{MVK_RUSSIAN_CAPITAL_SHA}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 1x12 0449 0429*/
		2,
		_Label_ {{"\xd1\x89"},{"\xd0\xa9"},{"\xd0\xa9"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		2,
		_KeyVal_ {{"\xd1\x89"},{"\xd0\xa9"},{"\xd0\xa9"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_SHCA},{MVK_RUSSIAN_CAPITAL_SHCA},{MVK_RUSSIAN_CAPITAL_SHCA}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 1x1 0430 0410*/
		2,
		_Label_ {{"\xd0\xb0"},{"\xd0\x90"},{"\xd0\x90"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		2,
		_KeyVal_ {{"\xd0\xb0"},{"\xd0\x90"},{"\xd0\x90"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_A},{MVK_RUSSIAN_CAPITAL_A},{MVK_RUSSIAN_CAPITAL_A}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 1x2 0441 0421*/
		2,
		_Label_ {{"\xd1\x81"},{"\xd0\xa1"},{"\xd0\xa1"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		2,
		_KeyVal_{{"\xd1\x81"},{"\xd0\xa1"},{"\xd0\xa1"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_ES},{MVK_RUSSIAN_CAPITAL_ES},{MVK_RUSSIAN_CAPITAL_ES}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 1x3 0434 0414*/
		2,
		_Label_ {{"\xd0\xb4"},{"\xd0\x94"},{"\xd0\x94"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		2,
		_KeyVal_ {{"\xd0\xb4"},{"\xd0\x94"},{"\xd0\x94"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_DE},{MVK_RUSSIAN_CAPITAL_DE},{MVK_RUSSIAN_CAPITAL_DE}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 1x4 0444 0424*/
		1,
		_Label_ {{"\xd1\x84"},{"\xd0\xa4"},{"\xd0\xa4"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		1,
		_KeyVal_ {{"\xd1\x84"},{"\xd0\xa4"},{"\xd0\xa4"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_EF},{MVK_RUSSIAN_CAPITAL_EF},{MVK_RUSSIAN_CAPITAL_EF}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 1x5 0433 0413*/
		2,
		_Label_ {{"\xd0\xb3"},{"\xd0\x93"},{"\xd0\x93"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		1,
		_KeyVal_ {{"\xd0\xb3"},{"\xd0\x93"},{"\xd0\x93"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_GHE},{MVK_RUSSIAN_CAPITAL_GHE},{MVK_RUSSIAN_CAPITAL_GHE}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 1x6 0445 0425*/
		2,
		_Label_ {{"\xd1\x85"},{"\xd0\xa5"},{"\xd0\xa5"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		2,
		_KeyVal_ {{"\xd1\x85"},{"\xd0\xa5"},{"\xd0\xa5"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_HA},{MVK_RUSSIAN_CAPITAL_HA},{MVK_RUSSIAN_CAPITAL_HA}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 1x7 0439 0419*/
		2,
		_Label_ {{"\xd0\xb9"},{"\xd0\x99"},{"\xd0\x99"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		2,
		_KeyVal_ {{"\xd0\xb9"},{"\xd0\x99"},{"\xd0\x99"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_SHRTI},{MVK_RUSSIAN_CAPITAL_SHRTI},{MVK_RUSSIAN_CAPITAL_SHRTI}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 1x8 043A 041A*/
		2,
		_Label_ {{"\xd0\xba"},{"\xd0\x9a"},{"\xd0\x9a"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		2,
		_KeyVal_ {{"\xd0\xba"},{"\xd0\x9a"},{"\xd0\x9a"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_KA},{MVK_RUSSIAN_CAPITAL_KA},{MVK_RUSSIAN_CAPITAL_KA}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 1x9 043B 041B*/
		2,
		_Label_ {{"\xd0\xbb"},{"\xd0\x9b"},{"\xd0\x9b"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		2,
		_KeyVal_ {{"\xd0\xbb"},{"\xd0\x9b"},{"\xd0\x9b"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_EL},{MVK_RUSSIAN_CAPITAL_EL},{MVK_RUSSIAN_CAPITAL_EL}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 1x10 0447 0427*/
		2,
		_Label_ {{"\xd1\x87"},{"\xd0\xa7"},{"\xd0\xa7"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		2,
		_KeyVal_ {{"\xd1\x87"},{"\xd0\xa7"},{"\xd0\xa7"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_CHE},{MVK_RUSSIAN_CAPITAL_CHE},{MVK_RUSSIAN_CAPITAL_CHE}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 1x11 044D 042D*/
		2,
		_Label_ {{"\xd1\x8d"},{"\xd0\xad"},{"\xd0\xad"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		2,
		_KeyVal_ {{"\xd1\x8d"},{"\xd0\xad"},{"\xd0\xad"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_E},{MVK_RUSSIAN_CAPITAL_E},{MVK_RUSSIAN_CAPITAL_E}},
		"",
		0,
		FALSE,
	},
	/*third line*/
	{
		USED, /* 3x1 */
		1,
		_Label_ {{""},{""},{""}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"textinput_qwerty_icon_shift_01.png","textinput_qwerty_icon_shift_02.png","textinput_qwerty_icon_shift_01.png"}, {"textinput_qwerty_icon_shift_02.png","textinput_qwerty_icon_shift_01.png","textinput_qwerty_icon_shift_01.png"}, {"textinput_qwerty_icon_shift_03.png","textinput_qwerty_icon_shift_02.png","textinput_qwerty_icon_shift_01.png"}},
		_BGImg_ {{"textinput_qwerty_button_function.png","textinput_qwerty_button_press.png","textinput_qwerty_button_function.png"}, {"textinput_qwerty_button_function.png","textinput_qwerty_button_press.png","textinput_qwerty_button_function.png"}, {"textinput_qwerty_button_function.png","textinput_qwerty_button_function.png","textinput_qwerty_button_nml.png"}},
		1,
		_KeyVal_ {{""},{""},{""}},
		_KeyEvt_ {{UD_MVK_SHIFT},{UD_MVK_SHIFT},{UD_MVK_SHIFT}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 3x2 0437 0417*/
		2,
		_Label_ {{"\xd0\xb7"},{"\xd0\x97"},{"\xd0\x97"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		2,
		_KeyVal_ {{"\xd0\xb7"},{"\xd0\x97"},{"\xd0\x97"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_ZE},{MVK_RUSSIAN_CAPITAL_ZE},{MVK_RUSSIAN_CAPITAL_ZE}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 3x3 044C 042C*/
		2,
		_Label_ {{"\xd1\x8c"},{"\xd0\xac"},{"\xd0\xac"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		2,
		_KeyVal_ {{"\xd1\x8c"},{"\xd0\xac"},{"\xd0\xac"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_SOFT},{MVK_RUSSIAN_CAPITAL_SOFT},{MVK_RUSSIAN_CAPITAL_SOFT}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 3x4 0446 0426*/
		2,
		_Label_ {{"\xd1\x86"},{"\xd0\xa6"},{"\xd0\xa6"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		2,
		_KeyVal_ {{"\xd1\x86"},{"\xd0\xa6"},{"\xd0\xa6"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_TSE},{MVK_RUSSIAN_CAPITAL_TSE},{MVK_RUSSIAN_CAPITAL_TSE}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 3x5 0432 0412*/
		2,
		_Label_ {{"\xd0\xb2"},{"\xd0\x92"},{"\xd0\x92"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		2,
		_KeyVal_ {{"\xd0\xb2"},{"\xd0\x92"},{"\xd0\x92"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_VE},{MVK_RUSSIAN_CAPITAL_VE},{MVK_RUSSIAN_CAPITAL_VE}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 3x6 0431 0411*/
		2,
		_Label_ {{"\xd0\xb1"},{"\xd0\x91"},{"\xd0\x91"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		2,
		_KeyVal_ {{"\xd0\xb1"},{"\xd0\x91"},{"\xd0\x91"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_BE},{MVK_RUSSIAN_CAPITAL_BE},{MVK_RUSSIAN_CAPITAL_BE}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 3x7 043D 041D*/
		2,
		_Label_ {{"\xd0\xbd"},{"\xd0\x9d"},{"\xd0\x9d"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		2,
		_KeyVal_ {{"\xd0\xbd"},{"\xd0\x9d"},{"\xd0\x9d"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_EN},{MVK_RUSSIAN_CAPITAL_EN},{MVK_RUSSIAN_CAPITAL_EN}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 3x8 043C 041C*/
		2,
		_Label_ {{"\xd0\xbc"},{"\xd0\x9c"},{"\xd0\x9c"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		2,
		_KeyVal_ {{"\xd0\xbc"},{"\xd0\x9c"},{"\xd0\x9c"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_EM},{MVK_RUSSIAN_CAPITAL_EM},{MVK_RUSSIAN_CAPITAL_EM}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 3x9 044A 042A*/
		2,
		_Label_ {{"\xd1\x8a"},{"\xd0\xaa"},{"\xd0\xaa"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		2,
		_KeyVal_ {{"\xd1\x8a"},{"\xd0\xaa"},{"\xd0\xaa"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_HARD},{MVK_RUSSIAN_CAPITAL_HARD},{MVK_RUSSIAN_CAPITAL_HARD}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 3x10 044E 042E*/
		2,
		_Label_ {{"\xd1\x8e"},{"\xd0\xae"},{"\xd0\xae"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		2,
		_KeyVal_ {{"\xd1\x8e"},{"\xd0\xae"},{"\xd0\xae"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_YU},{MVK_RUSSIAN_CAPITAL_YU},{MVK_RUSSIAN_CAPITAL_YU}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 3x11 0451 0401*/
		2,
		_Label_ {{"\xd1\x91"},{"\xd0\x81"},{"\xd0\x81"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_ {{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		2,
		_KeyVal_ {{"\xd1\x91"},{"\xd0\x81"},{"\xd0\x81"}},
		_KeyEvt_ {{MVK_RUSSIAN_SMALL_IO},{MVK_RUSSIAN_CAPITAL_IO},{MVK_RUSSIAN_CAPITAL_IO}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 3x12 */
		1,
		_Label_ {{""},{""},{""}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_ {{"textinput_qwerty_icon_clear.png","textinput_qwerty_icon_clear.png"}, {"textinput_qwerty_icon_clear.png","textinput_qwerty_icon_clear.png"}, {"textinput_qwerty_icon_clear.png","textinput_qwerty_icon_clear.png"}},
		_BGImg_ {{"textinput_qwerty_button_function.png","textinput_qwerty_button_press.png","textinput_qwerty_button_function.png"}, {"textinput_qwerty_button_function.png","textinput_qwerty_button_press.png","textinput_qwerty_button_function.png"}, {"textinput_qwerty_button_function.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}},
		1,
		_KeyVal_ {{""},{""},{""}},
		_KeyEvt_{{MVK_BackSpace},{MVK_BackSpace},{MVK_BackSpace}},
		"",
		0,
		TRUE,
	},
	/*fourth line*/

	{
		USED, /* 4x1 */
		1,
		_Label_{{"RU"},{"RU"},{"RU"}},
		LABEL_PROPERTIES_QTY_BOTTOM_LINE_IMAGE_TYPE,
		_LabelImg_{{"language_icon_port.png","language_icon_port.png"}, {"language_icon_port.png","language_icon_port.png"}, {"language_icon_port.png","language_icon_port.png"}},
		_BGImg_{{"textinput_qwerty_button_function.png","textinput_qwerty_button_press.png","textinput_qwerty_button_function.png"}, {"textinput_qwerty_button_function.png","textinput_qwerty_button_press.png","textinput_qwerty_button_function.png"}, {"textinput_qwerty_button_function.png","textinput_qwerty_button_function.png","textinput_qwerty_button_nml.png"}},
		1,
		_KeyVal_{{""},{""},{""}},
		_KeyEvt_ {{UD_MVK_LANG_CHANGE},{UD_MVK_LANG_CHANGE},{UD_MVK_LANG_CHANGE}},
		"OptionWindow",
		UD_MVK_OPTION_WINDOW,
		FALSE,
	},
	{
		USED, /* 4x2 */
		1,
		_Label_{{""},{""},{""}},
		LABEL_PROPERTIES_QTY_BOTTOM_LINE_TYPE,
		_LabelImg_ {{"symbol_icon_port.png","symbol_icon_port.png"}, {"symbol_icon_port.png","symbol_icon_port.png"}, {"symbol_icon_port.png","symbol_icon_port.png"}},
		_BGImg_{{"textinput_qwerty_button_function.png","textinput_qwerty_button_press.png","textinput_qwerty_button_function.png"}, {"textinput_qwerty_button_function.png","textinput_qwerty_button_press.png","textinput_qwerty_button_function.png"}, {"textinput_qwerty_button_function.png","textinput_qwerty_button_function.png","textinput_qwerty_button_nml.png"}},
		1,
		_KeyVal_{{""},{""},{""}},
		_KeyEvt_ {{UD_MVK_SYM},{UD_MVK_SYM},{UD_MVK_SYM}},
		"",
		0,
		FALSE,
	},

	/* Default SubLayout */
	{
		USED, /* 4x3 */
		1,
		_Label_{{""},{""},{""}},
		LABEL_PROPERTIES_QTY_SPACE_KEY_TYPE,
		_LabelImg_ {{"textinput_icon_space.png","textinput_icon_space_press.png"}, {"textinput_icon_space.png","textinput_icon_space_press.png"}, {"textinput_icon_space.png","textinput_icon_space_press.png"}},
		_BGImg_{{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		1,
		_KeyVal_{{""},{""},{""}},
		_KeyEvt_{{MVK_space},{MVK_space},{MVK_space}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 4x4 */
		3,
        _Label_{{".",""}, {".",""}, {".",""}},
		LABEL_PROPERTIES_QTY_BOTTOM_LINE_TYPE,
        _LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_{{"textinput_qwerty_button_function.png","textinput_qwerty_button_press.png"}, {"textinput_qwerty_button_function.png","textinput_qwerty_button_press.png"}, {"textinput_qwerty_button_function.png","textinput_qwerty_button_press.png"}},
		1,
		_KeyVal_{{""},{""},{""}},
        _KeyEvt_ {{MVK_period},{MVK_period},{MVK_period}},
		"",
		0,
		FALSE,
	},
	/* WithVoice SubLayout */
	{
		USED, /* 4x3 */
		1,
		_Label_{{""},{""},{""}},
		LABEL_PROPERTIES_QTY_BOTTOM_LINE_TYPE,
		_LabelImg_ {{"camera_qwerty_kor-moa_port.png","camera_qwerty_kor-moa_port.png","camera_qwerty_kor-moa_port.png"}, {"camera_qwerty_kor-moa_port.png","camera_qwerty_kor-moa_port.png","camera_qwerty_kor-moa_port.png"}, {"camera_qwerty_kor-moa_port.png","camera_qwerty_kor-moa_port.png","camera_qwerty_kor-moa_port.png"}},
		_BGImg_{{"textinput_qwerty_button_function.png","textinput_qwerty_button_press.png","textinput_qwerty_button_function.png"}, {"textinput_qwerty_button_function.png","textinput_qwerty_button_press.png","textinput_qwerty_button_function.png"}, {"textinput_qwerty_button_function.png","textinput_qwerty_button_press.png","textinput_qwerty_button_function.png"}},
		1,
		_KeyVal_{{""},{""},{""}},
		_KeyEvt_ {{0},{0},{0}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 4x4 */
		1,
		_Label_{{""},{""},{""}},
		LABEL_PROPERTIES_QTY_SPACE_KEY_TYPE,
		_LabelImg_ {{"textinput_icon_space.png","textinput_icon_space_press.png"}, {"textinput_icon_space.png","textinput_icon_space_press.png"}, {"textinput_icon_space.png","textinput_icon_space_press.png"}},
		_BGImg_{{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		1,
		_KeyVal_{{""},{""},{""}},
		_KeyEvt_{{MVK_space},{MVK_space},{MVK_space}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 4x5 */
		3,
        _Label_{{".",""}, {".",""}, {".",""}},
		LABEL_PROPERTIES_QTY_BOTTOM_LINE_TYPE,
        _LabelImg_ {{"",""}, {"",""}, {"",""}},
		_BGImg_{{"textinput_qwerty_button_function.png","textinput_qwerty_button_press.png"}, {"textinput_qwerty_button_function.png","textinput_qwerty_button_press.png"}, {"textinput_qwerty_button_function.png","textinput_qwerty_button_press.png"}},
		1,
		_KeyVal_{{""},{""},{""}},
        _KeyEvt_ {{MVK_period},{MVK_period},{MVK_period}},
		"",
		0,
		FALSE,
	},
	// }
	/* URL SubLayout */
	// {
	{
		USED, /* 4x3 */
		1,
		_Label_{{""},{""},{""}},
		LABEL_PROPERTIES_QTY_SPACE_KEY_TYPE,
		_LabelImg_ {{"textinput_icon_space.png","textinput_icon_space_press.png"}, {"textinput_icon_space.png","textinput_icon_space_press.png"}, {"textinput_icon_space.png","textinput_icon_space_press.png"}},
		_BGImg_{{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		1,
		_KeyVal_{{""},{""},{""}},
		_KeyEvt_{{MVK_space},{MVK_space},{MVK_space}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 4x4 */
		1,
		_Label_{{"/"},{"/"},{"/"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_{{" "," "}, {" "," "}, {" "," "}},
		_BGImg_{{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}},
		1,
		_KeyVal_{{"/"},{"/"},{"/"}},
		_KeyEvt_ {{MVK_slash},{MVK_slash},{MVK_slash}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 4x5 */
		1,
		_Label_{{"www."},{"www."},{"www."}},
		LABEL_PROPERTIES_QTY_WWW_TYPE,
		_LabelImg_{{" "," "}, {" "," "}, {" "," "}},
		_BGImg_{{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}},
		1,
		_KeyVal_{{"www."},{"www."},{"www."}},
		_KeyEvt_ {{0},{0},{0}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 4x6 */
		3,
		_Label_{{".",""}, {".",""}, {".",""}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_{{" "," "}, {" "," "}, {" "," "}},
		_BGImg_{{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}},
		1,
		_KeyVal_{{"."},{"."},{"."}},
		_KeyEvt_ {{MVK_period},{MVK_period},{MVK_period}},
		"",
		0,
		FALSE,
	},
	// }
	/* Email SubLayout */
	// {
	{
		USED, /* 4x3 */
		1,
		_Label_{{""},{""},{""}},
		LABEL_PROPERTIES_QTY_SPACE_KEY_TYPE,
		_LabelImg_ {{"textinput_icon_space.png","textinput_icon_space_press.png"}, {"textinput_icon_space.png","textinput_icon_space_press.png"}, {"textinput_icon_space.png","textinput_icon_space_press.png"}},
		_BGImg_{{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_capslock_press.png"}},
		1,
		_KeyVal_{{""},{""},{""}},
		_KeyEvt_{{MVK_space},{MVK_space},{MVK_space}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 4x4 */
		1,
		_Label_{{"@"},{"@"},{"@"}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_{{" "," "}, {" "," "}, {" "," "}},
		_BGImg_{{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}},
		1,
		_KeyVal_{{"@"},{"@"},{"@"}},
		_KeyEvt_ {{MVK_at},{MVK_at},{MVK_at}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 4x5 */
		1,
		_Label_{{".com"},{".com"},{".com"}},
		LABEL_PROPERTIES_QTY_WWW_TYPE,
		_LabelImg_{{" "," "}, {" "," "}, {" "," "}},
		_BGImg_{{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}},
		1,
		_KeyVal_{{".com"},{".com"},{".com"}},
		_KeyEvt_ {{0},{0},{0}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 4x6 */
		3,
		_Label_{{".",""}, {".",""}, {".",""}},
		LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
		_LabelImg_{{" "," "}, {" "," "}, {" "," "}},
		_BGImg_{{"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}, {"textinput_qwerty_button_nml.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}},
		1,
		_KeyVal_{{"."},{"."},{"."}},
		_KeyEvt_ {{MVK_period},{MVK_period},{MVK_period}},
		"",
		0,
		FALSE,
	},
	{
		USED, /* 4x5 */
		1,
		_Label_ {{""},{""},{""}},
		LABEL_PROPERTIES_QTY_BOTTOM_LINE_TYPE,
		_LabelImg_ {{"textinput_qwerty_icon_enter.png","textinput_qwerty_icon_enter.png","textinput_qwerty_icon_enter_disabled.png"}, {"textinput_qwerty_icon_enter.png","textinput_qwerty_icon_enter.png","textinput_qwerty_icon_enter_disabled.png"}, {"textinput_qwerty_icon_enter.png","textinput_qwerty_icon_enter.png","textinput_qwerty_icon_enter_disabled.png"}},
		_BGImg_ {{"textinput_qwerty_button_function.png","textinput_qwerty_button_press.png","textinput_qwerty_button_function.png"}, {"textinput_qwerty_button_function.png","textinput_qwerty_button_press.png","textinput_qwerty_button_function.png"}, {"textinput_qwerty_button_function.png","textinput_qwerty_button_press.png","textinput_qwerty_button_nml.png"}},
		1,
		_KeyVal_ {{""},{""},{""}},
		_KeyEvt_{{MVK_Return},{MVK_Return},{MVK_Return}},
		"",
		0,
		FALSE,
	},

	{NOT_USED,},
}
#endif


