/*
 * Copyright 2012  Samsung Electronics Co., Ltd
 *
 * Licensed under the Flora License, Version 1.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.tizenopensource.org/license
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "mcftypes.h"
#include "mcfconfig.h"
#include "mcfstructs.h"
#include "mcfkeydefines.h"
#include <Ecore_IMF.h>

/* This prevents "deprecated conversion" warnings.. */
#pragma GCC diagnostic ignored "-Wwrite-strings"

#ifndef __MCF_RESOURCE_H__
#define __MCF_RESOURCE_H__

#define FONT_PROPERTIES_FILE "fontprop.dat"

#define PORTRAIT_DEFAULT_BG_IMG "textinput_panel_bg.png"
#define LANDSCAPE_DEFAULT_BG_IMG "textinput_panel_land_bg.png"

#define POPUP_BG_IMG "B09_bg_Popup.png"

#define RESOURCE_DATA_LABEL_LEN 10
#define RESOURCE_DATA_IMG_PATH_LEN 50
#define RESOURCE_DATA_KEY_VALUE_LEN 8
#define RESOURCE_DATA_AUTOPOPUP_KEY_LEN 4

/* User defined key list */
typedef enum _MCFUserDefinedKey {
	UD_MVK_START = (MVK_RESERVED_KEY + 1), /* KEY_TYPE_CONTROL */
	/* Add here */
	UD_MVK_OPTION,
	UD_MVK_LANGUAGE,
	UD_MVK_CHANGEISE,
	UD_MVK_HIDE,
	UD_MVK_SHIFT,
	UD_MVK_OK,
	UD_MVK_MORE,
	UD_MVK_PREDICTION_ONOFF,
	UD_MVK_ABC,
	UD_MVK_123,
	UD_MVK_SYM,
	UD_MVK_PREVSYM,
	UD_MVK_NEXTSYM,
	UD_MVK_KEYPAD,
	UD_MVK_KEYPAD_4X4,
	UD_MVK_KEYPAD_QTY,
	UD_MVK_COMPLETION_MUL_abc,
	UD_MVK_COMPLETION_MUL_Abc,
	UD_MVK_COMPLETION_MUL_ABC,
	UD_MVK_IPv6,
	UD_MVK_LANG_CHANGE,
	UD_MVK_OPTION_WINDOW,
#ifdef SUPPORTS_VOICE_INPUT
	UD_MVK_VOICE_WINDOW,
#endif
	UD_MVK_END /* End of the user defined key value*/
}MCFUserDefinedKey;

/* Custom ID for setting private keys */
enum _MCFCustomID {
	CUSTOMID_PREDICTION,
	CUSTOMID_ENTER,
	CUSTOMID_WWWCOM,
	CUSTOMID_BACKSPACE,
	CUSTOMID_MAX
};

enum MCFSubLayoutID {
	SUBLAYOUTID_NONE = -1,
	SUBLAYOUTID_DEFAULT = 0,
	SUBLAYOUTID_WITH_VOICE,
	SUBLAYOUTID_URL,
	SUBLAYOUTID_EMAIL,

	SUBLAYOUTID_MAX
};

#define MAX_KEY 60

/**@brief  Layout definition */
typedef enum _MCFLayout {
	/* base layout */
	LYT_PORTRAIT_4X4_DEFAULT = 0,
	LYT_PORTRAIT_4X4_SYM,
	LYT_PORTRAIT_4X4_IPv6_123,
	LYT_PORTRAIT_4X4_IPv6_ABC,
	LYT_PORTRAIT_4X4_NUMONLY,
	LYT_PORTRAIT_4X4_MONTH,
	LYT_PORTRAIT_QTY_DEFAULT,
	LYT_PORTRAIT_AZT_DEFAULT,
	LYT_PORTRAIT_QTY_URL,
	LYT_PORTRAIT_QTY_EMAIL,
	 /*russian layouts*/
	LYT_PORTRAIT_QTY_RUSSIAN,
	LYT_LANDSCAPE_QTY_RUSSIAN,
	/*Landscape Layouts*/
	LYT_LANDSCAPE_QTY_DEFAULT,
	LYT_LANDSCAPE_AZT_FRENCH,
	LYT_LANDSCAPE_QTY_URL,
	LYT_LANDSCAPE_QTY_EMAIL,
	LYT_LANDSCAPE_4X4_NUM,
	LYT_LANDSCAPE_4X4_PASSWD,
	LYT_LANDSCAPE_4X4_IPv6_123,
	LYT_LANDSCAPE_4X4_IPv6_ABC,
	LYT_LANDSCAPE_4X4_NUMONLY,

	/* popup layout */
	LYT_PORTRAIT_4X4_TEXTMODE_POPUP,

	LYT_PUNCTUATION_POPUP,
	LYT_EMOTICON_POPUP,
	LYT_URL_POPUP,

	MAX_LAYOUT
}MCFLayout;

extern McfLayout mcf_layout[MAX_LAYOUT];

/**@brief  Input Mode definition */
typedef enum _MCFInputMode {
	/* base input mode */
	INPUT_MODE_4X4_ENGLISH = 0,
	INPUT_MODE_4X4_NUM,
	INPUT_MODE_4X4_SYM_1,
	INPUT_MODE_4X4_SYM_2,
	INPUT_MODE_4X4_SYM_3,
	INPUT_MODE_4X4_SYM_4,
	INPUT_MODE_4X4_SYM_5,
	INPUT_MODE_4X4_TELEPHONE,
	INPUT_MODE_4X4_URL,
	INPUT_MODE_4X4_EMAIL,
	INPUT_MODE_4X4_PASSWD,
	INPUT_MODE_4X4_IPv6_123,
	INPUT_MODE_4X4_IPv6_ABC,
	INPUT_MODE_4X4_NUMONLY,
	INPUT_MODE_4X4_MONTH,

	INPUT_MODE_4X4_FRENCH,
	INPUT_MODE_4X4_SPANISH,
	INPUT_MODE_4X4_ITALIAN,
	INPUT_MODE_4X4_DUTCH,
	INPUT_MODE_4X4_PORTUGUESE,
	INPUT_MODE_4X4_GERMAN,

	INPUT_MODE_4X4_TURKISH,
	INPUT_MODE_4X4_GREEK,
	INPUT_MODE_4X4_RUSSIAN,

	INPUT_MODE_QTY_ENGLISH,
	INPUT_MODE_QTY_URL,
	INPUT_MODE_QTY_EMAIL,
	INPUT_MODE_QTY_SYM_1,
	INPUT_MODE_QTY_SYM_2,
	INPUT_MODE_QTY_SYM_3,
	INPUT_MODE_QTY_SYM_4,

	INPUT_MODE_QTY_FRENCH,
	/* Below 5 modes are equivalent to english mode */
	INPUT_MODE_QTY_SPANISH,
	INPUT_MODE_QTY_ITALIAN,
	INPUT_MODE_QTY_DUTCH,
	INPUT_MODE_QTY_PORTUGUESE,
	INPUT_MODE_QTY_GERMAN,

	INPUT_MODE_QTY_TURKISH,
	INPUT_MODE_QTY_GREEK,
	INPUT_MODE_QTY_RUSSIAN,

	MAX_INPUT_MODE
}MCFInputMode;

extern McfInputModeConfigure mcf_input_mode_configure[MAX_INPUT_MODE];

typedef enum _MCFInputModePopup {
	/* add popup input mode */
	INPUT_MODE_4X4_TEXTMODE_POPUP,
	INPUT_MODE_PUNCTUATION_POPUP,
	INPUT_MODE_EMOTICON_POPUP,
	INPUT_MODE_URL_POPUP,
	INPUT_MODE_SCENETEXT_POPUP,
	MAX_INPUT_MODE_POPUP
}MCFInputModePopup;

extern McfInputModePopupConfigure mcf_input_mode_popup_configure[MAX_INPUT_MODE_POPUP];
extern mcfboolean mcf_sublayout_support_table[MAX_INPUT_MODE][SUBLAYOUTID_MAX];

#define DEFAULT_FONT_NAME "SLP:style=medium"
#define DEFAULT_FONT_SIZE  40

typedef enum _MCFLabelProperties {
	LABEL_PROPERTIES_4X4_DEFAULT_TYPE = 0,
	LABEL_PROPERTIES_4X4_SIDE_BUTTON_TYPE,
	LABEL_PROPERTIES_4X4_SIDE_UIITEM_TYPE,
	LABEL_PROPERTIES_4X4_SOFTKEYBAR_TYPE,
	LABEL_PROPERTIES_4X4_NUM_TYPE,
	LABEL_PROPERTIES_4X4_SYM_PAGELABEL,
	LABEL_PROPERTIES_QTY_DEFAULT_TYPE,
	LABEL_PROPERTIES_QTY_BOTTOM_LINE_TYPE,
	LABEL_PROPERTIES_QTY_BOTTOM_LINE_IMAGE_TYPE,
	LABEL_PROPERTIES_TEXTMODE_POPUP_TYPE,
	LABEL_PROPERTIES_4X4_ASTERISK_TYPE,
	LABEL_PROPERTIES_QTY_WWW_TYPE,
	LABEL_PROPERTIES_4x4_WWW_TYPE,
	LABEL_PROPERTIES_LANGNAME,
	LABEL_PROPERTIES_LAND_DEFAULT_TYPE,
	LABEL_PROPERTIES_LAND_DEFAULT_IMAGE_TYPE,
	LABEL_PROPERTIES_LAND_MODE_CHANGE_LABEL_TYPE,
	LABEL_PROPERTIES_LAND_SYMBOL_LABEL_TYPE,
	LABEL_PROPERTIES_LAND_WWW_TYPE,
	LABEL_PROPERTIES_4X4_INDIC_TYPE,
	LABEL_PROPERTIES_4x4_MONTH_TYPE,
	LABEL_PROPERTIES_LAND_IP_ABC,
	LABEL_PROPERTIES_LAND_MONTH,

	LABEL_PROPERTIES_PUNTUATION_BUTTON_TYPE,
	LABEL_PROPERTIES_QTY_SPACE_KEY_TYPE,
	LABEL_PROPERTIES_QTY_DOT_BUTTON_TYPE,
	LABEL_PROPERTIES_QTY_NUM_DEFAULT_TYPE,
	LABEL_PROPERTIES_URL_POPUP_TYPE,

	MAX_LABEL_PROPERTIES
}MCFLabelProperties;

#define COLOR_1 { 255, 255, 255, 255}
#define COLOR_2 { 0, 0, 0 , 255}
#define COLOR_25 { 0, 186, 255 , 255}
#define COLOR_61 { 28, 31, 36 , 255}
#define COLOR_49 { 36, 36, 36 , 255}
#define COLOR_18 { 0, 161, 253 , 255}
#define COLOR_71 { 75, 75, 75, 255}

#define COLOR_242 { 255, 255, 255, 255}
#define COLOR_PRESSED { 43, 43, 43, 255}
#define COLOR_LIGHTGRAY { 150, 150, 150, 255}
#define COLOR_SPACE { 255, 255, 255, 255}

#define COLOR_LABEL_PRESSED { 120, 120, 120, 255 }
#define COLOR_LABEL_DISABLED { 96, 96, 96, 255 }

#define COLOR_NORMAL {23,23,23,255}
#define COLOR_NORMAL_LONGKEY {150,150,150,255}
#define COLOR_SHIFT_STATE_COLOR {255,180,0,255}
#define COLOR_FUNCTION { 255, 255, 255, 255}
#define COLOR_PHONENUMBER_TEXT { 150,150,150,255 }
#define COLOR_DISABLED { 178, 178, 178, 255 }

static McfLabelProperties mcf_key_label_properties[MAX_LABEL_PROPERTIES][MAX_SIZE_OF_LABEL_FOR_ONE] = {
	/* fValid, fontName, fontSize, normalColor, activeColor, selectedColor, alignment, padding, shadowDistance, shadowDirection, shadowColor  */
	/* LABEL_PROPERTIES_4X4_DEFAULT_TYPE */
	{
	{USED, DEFAULT_FONT_NAME, 30,
		{
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},
	LABEL_ALIGN_CENTER_TOP, 0, 10},
	{USED, DEFAULT_FONT_NAME, 21,
		{
			{COLOR_PHONENUMBER_TEXT, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_PHONENUMBER_TEXT, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_PHONENUMBER_TEXT, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},LABEL_ALIGN_CENTER_TOP, 0, 42},
		{FALSE},
	},
	/* LABEL_PROPERTIES_4X4_SIDE_BUTTON_TYPE*/
	{
		{USED, DEFAULT_FONT_NAME, 35,
		{
			{COLOR_242, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_242, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_242, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},LABEL_ALIGN_CENTER_MIDDLE, 0},
			{FALSE},
	},
	/* LABEL_PROPERTIES_4X4_SIDE_UIITEM_TYPE*/
	{
		{USED, DEFAULT_FONT_NAME, 35,
		{
			{COLOR_DISABLED, COLOR_DISABLED, COLOR_DISABLED},
			{COLOR_DISABLED, COLOR_DISABLED, COLOR_DISABLED},
			{COLOR_DISABLED, COLOR_DISABLED, COLOR_DISABLED},
		},
		LABEL_ALIGN_CENTER_MIDDLE, 0},
		{FALSE},
	},
	/* LABEL_PROPERTIES_4X4_SOFTKEYBAR_TYPE*/
	{
		{USED, DEFAULT_FONT_NAME, 24,
		{
			{COLOR_242, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_242, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_242, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},LABEL_ALIGN_CENTER_MIDDLE, 0},
		{FALSE},
	},
	/* LABEL_PROPERTIES_4X4_NUM_TYPE*/
	{
		{USED, DEFAULT_FONT_NAME, 44,
		{
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},LABEL_ALIGN_CENTER_MIDDLE, 0},
		{FALSE},
	},
	/* LABEL_PROPERTIES_4X4_SYM_PAGELABEL*/
	{
		{USED, DEFAULT_FONT_NAME, 30,
		{
			{COLOR_242, COLOR_242, COLOR_LABEL_DISABLED},
			{COLOR_242, COLOR_242, COLOR_LABEL_DISABLED},
			{COLOR_242, COLOR_242, COLOR_LABEL_DISABLED},
			},LABEL_ALIGN_CENTER_MIDDLE, 0},
		{FALSE},
	},
	/* LABEL_PROPERTIES_QTY_DEFAULT_TYPE */
	{
	{USED, DEFAULT_FONT_NAME, 42,
		{
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},
		LABEL_ALIGN_CENTER_MIDDLE, 0},
	{USED, DEFAULT_FONT_NAME, 23,
		{
			{COLOR_NORMAL_LONGKEY, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL_LONGKEY, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL_LONGKEY, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},
		LABEL_ALIGN_RIGHT_TOP, 8, 2},
		{FALSE},
	},
	/* LABEL_PROPERTIES_QTY_BOTTOM_LINE_TYPE */
	{
	{USED, DEFAULT_FONT_NAME, 26,
		{
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},LABEL_ALIGN_CENTER_MIDDLE, 0},
	{USED, DEFAULT_FONT_NAME, 28,
		{
			{COLOR_LIGHTGRAY, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_LIGHTGRAY, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_LIGHTGRAY, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},LABEL_ALIGN_CENTER_TOP, 0, 10},
	{USED, DEFAULT_FONT_NAME, 42,
		{
			{COLOR_242, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_242, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_242, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},LABEL_ALIGN_CENTER_BOTTOM, 0, 10},
		{FALSE},
	},
	/* LABEL_PROPERTIES_QTY_BOTTOM_LINE_IMAGE_TYPE */
	{
		{USED, DEFAULT_FONT_NAME, 22,
		{
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},LABEL_ALIGN_CENTER_BOTTOM, 10, 6},
		{FALSE},
	},
	/* LABEL_PROPERTIES_TEXTMODE_POPUP_TYPE */
	{
	{USED, DEFAULT_FONT_NAME, 22,
		{
			{COLOR_49, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_49, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_49, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},LABEL_ALIGN_CENTER_MIDDLE, 0},
		{FALSE},
	},
	/* LABEL_PROPERTIES_4X4_ASTERISK_TYPE */
	{
		{USED, DEFAULT_FONT_NAME, 34,
		{
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},LABEL_ALIGN_CENTER_MIDDLE, 0},
	{USED, DEFAULT_FONT_NAME, 34,
		{
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},LABEL_ALIGN_LEFT_MIDDLE, 30, 5},
	{USED, DEFAULT_FONT_NAME, 34,
		{
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},LABEL_ALIGN_CENTER_MIDDLE, 15, 0},
		{FALSE},
	},
	/* LABEL_PROPERTIES_QTY_WWW_TYPE */
	{
	{USED, DEFAULT_FONT_NAME, 32,
		{
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},LABEL_ALIGN_CENTER_MIDDLE, 0},
		{FALSE},
	},

	/* LABEL_PROPERTIES_4x4_WWW_TYPE */
	{
	{USED, DEFAULT_FONT_NAME, 32,
		{
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},LABEL_ALIGN_CENTER_MIDDLE, 0},
		{FALSE},
	},
	/* LABEL_PROPERTIES_LANGNAME */
	{
	{USED, DEFAULT_FONT_NAME, 20,
		{
			{COLOR_LABEL_PRESSED, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_LABEL_PRESSED, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_LABEL_PRESSED, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},LABEL_ALIGN_LEFT_MIDDLE, 0},
		{FALSE},
	},

	/*LABEL_PROPERTIES_LAND_DEFAULT_TYPE*/
	{
	{USED, DEFAULT_FONT_NAME, 42,
		{
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		}, LABEL_ALIGN_CENTER_MIDDLE, 0},
	{USED, DEFAULT_FONT_NAME, 23,
		{
			{COLOR_LIGHTGRAY, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_LIGHTGRAY, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_LIGHTGRAY, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},LABEL_ALIGN_RIGHT_TOP, 7, 2},
		{FALSE},
	},


	/*LABEL_PROPERTIES_LAND_DEFAULT_IMAGE_TYPE*/
	{
	{USED, DEFAULT_FONT_NAME, 26,
		{
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},LABEL_ALIGN_RIGHT_MIDDLE, 20, 10},
	{FALSE},
	},

	/*LABEL_PROPERTIES_LAND_MODE_CHANGE_LABEL_TYPE*/
	{
	{USED, DEFAULT_FONT_NAME, 32,
		{
			{COLOR_242, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_242, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_242, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		}, LABEL_ALIGN_CENTER_MIDDLE, 0},
	{FALSE},
	},

	/*LABEL_PROPERTIES_LAND_SYMBOL_LABEL_TYPE*/
	{
	{USED, DEFAULT_FONT_NAME, 42,
		{
			{COLOR_242, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_242, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_242, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},LABEL_ALIGN_CENTER_BOTTOM, 0, 5},
	{USED, DEFAULT_FONT_NAME, 28,
		{
			{COLOR_LIGHTGRAY, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_LIGHTGRAY, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_LIGHTGRAY, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},LABEL_ALIGN_CENTER_TOP, 0, 5},
	{USED, DEFAULT_FONT_NAME, 42,
		{
			{COLOR_242, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_242, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_242, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},LABEL_ALIGN_CENTER_BOTTOM, 0, 5},
	{FALSE},

	},
	/* LABEL_PROPERTIES_LAND_WWW_TYPE */
	{
	{USED, DEFAULT_FONT_NAME, 30,
		{
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		}, LABEL_ALIGN_CENTER_MIDDLE, 0},
	{FALSE},
	},
	/* LABEL_PROPERTIES_4X4_INDIC_TYPE */
	{
	{USED, DEFAULT_FONT_NAME, 30,
		{
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},
	LABEL_ALIGN_CENTER_TOP, 0, 10},
	{USED, DEFAULT_FONT_NAME, 21,
		{
			{COLOR_PHONENUMBER_TEXT, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_PHONENUMBER_TEXT, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_PHONENUMBER_TEXT, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},LABEL_ALIGN_CENTER_TOP, 0, 42},
	{FALSE},
	},
	/* LABEL_PROPERTIES_4X4_MONTH_TYPE */
	{
	{USED, DEFAULT_FONT_NAME, 32,
		{
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},
	LABEL_ALIGN_CENTER_MIDDLE, 0},
	{FALSE},
	},
	/* LABEL_PROPERTIES_LAND_IP_ABC */
	{
	{USED, DEFAULT_FONT_NAME, 44,
		{
			{COLOR_FUNCTION, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_FUNCTION, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_FUNCTION, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},
	LABEL_ALIGN_CENTER_MIDDLE, 0},
	{FALSE},
	},
	/* LABEL_PROPERTIES_LAND_MONTH */
	{
	{USED, DEFAULT_FONT_NAME, 32,
		{
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},
	LABEL_ALIGN_CENTER_MIDDLE, 0},
	{FALSE},
	},
	/* LABEL_PROPERTIES_PUNTUATION_BUTTON_TYPE*/
	{
	{USED, DEFAULT_FONT_NAME, 48,
		{
			{COLOR_242, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_242, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_242, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		}, LABEL_ALIGN_CENTER_MIDDLE, 0},
	{FALSE},
	},
	/* LABEL_PROPERTIES_QTY_SPACE_KEY_TYPE */
	{
	{TRUE, DEFAULT_FONT_NAME, 25,
		{
			{COLOR_SPACE, COLOR_PRESSED, COLOR_DISABLED},
			{COLOR_SPACE, COLOR_PRESSED, COLOR_DISABLED},
			{COLOR_SPACE, COLOR_PRESSED, COLOR_DISABLED},
		},
	LABEL_ALIGN_CENTER_MIDDLE, 0},
	{TRUE, DEFAULT_FONT_NAME, 25,
		{
			{COLOR_SPACE, COLOR_PRESSED, COLOR_DISABLED},
			{COLOR_SPACE, COLOR_PRESSED, COLOR_DISABLED},
			{COLOR_SPACE, COLOR_PRESSED, COLOR_DISABLED},
		},
	LABEL_ALIGN_LEFT_TOP, 9, 0},
	{TRUE, DEFAULT_FONT_NAME, 25,
		{
			{COLOR_SPACE, COLOR_PRESSED, COLOR_DISABLED},
			{COLOR_SPACE, COLOR_PRESSED, COLOR_DISABLED},
			{COLOR_SPACE, COLOR_PRESSED, COLOR_DISABLED},
		},
	LABEL_ALIGN_RIGHT_TOP, 9, 0},
	{FALSE},
	},
	/* LABEL_PROPERTIES_QTY_DOT_BUTTON_TYPE */
	{
	{USED, DEFAULT_FONT_NAME, 56,
		{
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},
	LABEL_ALIGN_CENTER_BOTTOM, 0, 9},
	{FALSE},
	},
	/* LABEL_PROPERTIES_QTY_NUM_DEFAULT_TYPE */
	{
	{USED, DEFAULT_FONT_NAME, 30,
		{
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_NORMAL, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},
	LABEL_ALIGN_CENTER_MIDDLE, 0},
	{FALSE},
	},
	/* LABEL_PROPERTIES_URL_POPUP_TYPE */
	{
	{USED, DEFAULT_FONT_NAME, 36,
		{
			{COLOR_242, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_242, COLOR_PRESSED, COLOR_LABEL_DISABLED},
			{COLOR_242, COLOR_PRESSED, COLOR_LABEL_DISABLED},
		},
	LABEL_ALIGN_CENTER_MIDDLE, 0},
	{FALSE},
	},
};

typedef enum _McfKeyset {
	/* BASE */
	KEYSET_PORTRAIT_4X4_ENGLISH = 0,
	KEYSET_PORTRAIT_4X4_NUM,
	KEYSET_PORTRAIT_4X4_SYM_1,
	KEYSET_PORTRAIT_4X4_SYM_2,
	KEYSET_PORTRAIT_4X4_SYM_3,
	KEYSET_PORTRAIT_4X4_SYM_4,
	KEYSET_PORTRAIT_4X4_SYM_5,
	KEYSET_PORTRAIT_4x4_TELEPHONE,
	KEYSET_PORTRAIT_4X4_URL,
	KEYSET_PORTRAIT_4X4_EMAIL,
	KEYSET_PORTRAIT_4X4_PASSWD,
	KEYSET_PORTRAIT_4X4_IPv6_123,
	KEYSET_PORTRAIT_4X4_IPv6_ABC,
	KEYSET_PORTRAIT_4X4_NUMONLY,
	KEYSET_PORTRAIT_4X4_MONTH,

	KEYSET_PORTRAIT_4X4_FRENCH,
	KEYSET_PORTRAIT_4X4_SPANISH,
	KEYSET_PORTRAIT_4X4_ITALIAN,
	KEYSET_PORTRAIT_4X4_DUTCH,
	KEYSET_PORTRAIT_4X4_PORTUGUESE,
	KEYSET_PORTRAIT_4X4_GERMAN,

	KEYSET_PORTRAIT_4X4_TURKISH,
	KEYSET_PORTRAIT_4X4_GREEK,
	KEYSET_PORTRAIT_4X4_RUSSIAN,

	KEYSET_PORTRAIT_QTY_ENGLISH,
	KEYSET_PORTRAIT_QTY_URL,
	KEYSET_PORTRAIT_QTY_EMAIL,
	KEYSET_PORTRAIT_QTY_SYM_1,
	KEYSET_PORTRAIT_QTY_SYM_2,
	KEYSET_PORTRAIT_QTY_SYM_3,
	KEYSET_PORTRAIT_QTY_SYM_4,

	KEYSET_PORTRAIT_QTY_FRENCH,
	KEYSET_PORTRAIT_QTY_SPANISH,
	KEYSET_PORTRAIT_QTY_ITALIAN,
	KEYSET_PORTRAIT_QTY_DUTCH,
	KEYSET_PORTRAIT_QTY_PORTUGUESE,
	KEYSET_PORTRAIT_QTY_GERMAN,

	KEYSET_PORTRAIT_QTY_TURKISH,
	KEYSET_PORTRAIT_QTY_GREEK,
	KEYSET_PORTRAIT_QTY_RUSSIAN,

	KEYSET_LANDSCAPE_QTY_ENGLISH,
	KEYSET_LANDSCAPE_QTY_URL,
	KEYSET_LANDSCAPE_QTY_EMAIL,

	KEYSET_LANDSCAPE_QTY_FRENCH,
	KEYSET_LANDSCAPE_QTY_SPANISH,
	KEYSET_LANDSCAPE_QTY_ITALIAN,
	KEYSET_LANDSCAPE_QTY_DUTCH,
	KEYSET_LANDSCAPE_QTY_PORTUGUESE,
	KEYSET_LANDSCAPE_QTY_GERMAN,

	KEYSET_LANDSCAPE_QTY_TURKISH,
	KEYSET_LANDSCAPE_QTY_GREEK,
	KEYSET_LANDSCAPE_QTY_RUSSIAN,

	KEYSET_LANDSCAPE_4X4_NUM,
	KEYSET_LANDSCAPE_4X4_PASSWD,
	KEYSET_LANDSCAPE_4X4_IPv6_123,
	KEYSET_LANDSCAPE_4X4_IPv6_ABC,
	KEYSET_LANDSCAPE_4X4_NUMONLY,
	KEYSET_LANDSCAPE_4X4_MONTH,

	KEYSET_EMOTICON_POPUP,
	KEYSET_PUNCTUATION_POPUP,
	KEYSET_URL_POPUP,
	KEYSET_PORTRAIT_TEXTMODEPOPUP_4X4,

	MAX_KEYSET,
}McfKeyset;

static McfLayoutKeyset mcf_layout_keyset[] = {
	/* BASE */
	{INPUT_MODE_4X4_ENGLISH,		LYT_PORTRAIT_4X4_DEFAULT,			KEYSET_PORTRAIT_4X4_ENGLISH},
	{INPUT_MODE_4X4_NUM,			LYT_PORTRAIT_4X4_DEFAULT,			KEYSET_PORTRAIT_4X4_NUM},
	{INPUT_MODE_4X4_SYM_1,			LYT_PORTRAIT_4X4_SYM,				KEYSET_PORTRAIT_4X4_SYM_1},
	{INPUT_MODE_4X4_SYM_2,			LYT_PORTRAIT_4X4_SYM,				KEYSET_PORTRAIT_4X4_SYM_2},
	{INPUT_MODE_4X4_SYM_3,			LYT_PORTRAIT_4X4_SYM,				KEYSET_PORTRAIT_4X4_SYM_3},
	{INPUT_MODE_4X4_SYM_4,			LYT_PORTRAIT_4X4_SYM,				KEYSET_PORTRAIT_4X4_SYM_4},
	{INPUT_MODE_4X4_SYM_5,			LYT_PORTRAIT_4X4_SYM,				KEYSET_PORTRAIT_4X4_SYM_5},
	{INPUT_MODE_4X4_TELEPHONE,		LYT_PORTRAIT_4X4_DEFAULT,			KEYSET_PORTRAIT_4x4_TELEPHONE},
	{INPUT_MODE_4X4_URL,			LYT_PORTRAIT_4X4_DEFAULT,			KEYSET_PORTRAIT_4X4_URL},
	{INPUT_MODE_4X4_EMAIL,			LYT_PORTRAIT_4X4_DEFAULT,			KEYSET_PORTRAIT_4X4_EMAIL},
	{INPUT_MODE_4X4_PASSWD,			LYT_PORTRAIT_4X4_DEFAULT,			KEYSET_PORTRAIT_4X4_PASSWD},
	{INPUT_MODE_4X4_IPv6_123,		LYT_PORTRAIT_4X4_IPv6_123,			KEYSET_PORTRAIT_4X4_IPv6_123},
	{INPUT_MODE_4X4_IPv6_ABC,		LYT_PORTRAIT_4X4_IPv6_ABC,			KEYSET_PORTRAIT_4X4_IPv6_ABC},
	{INPUT_MODE_4X4_NUMONLY,		LYT_PORTRAIT_4X4_NUMONLY,			KEYSET_PORTRAIT_4X4_NUMONLY},
	{INPUT_MODE_4X4_MONTH,			LYT_PORTRAIT_4X4_MONTH,				KEYSET_PORTRAIT_4X4_MONTH},

	{INPUT_MODE_4X4_FRENCH,			LYT_PORTRAIT_4X4_DEFAULT,			KEYSET_PORTRAIT_4X4_FRENCH},
	{INPUT_MODE_4X4_SPANISH,		LYT_PORTRAIT_4X4_DEFAULT,			KEYSET_PORTRAIT_4X4_SPANISH},
	{INPUT_MODE_4X4_ITALIAN,		LYT_PORTRAIT_4X4_DEFAULT,			KEYSET_PORTRAIT_4X4_ITALIAN},
	{INPUT_MODE_4X4_DUTCH,			LYT_PORTRAIT_4X4_DEFAULT,			KEYSET_PORTRAIT_4X4_DUTCH},
	{INPUT_MODE_4X4_PORTUGUESE,		LYT_PORTRAIT_4X4_DEFAULT,			KEYSET_PORTRAIT_4X4_PORTUGUESE},
	{INPUT_MODE_4X4_GERMAN,			LYT_PORTRAIT_4X4_DEFAULT,			KEYSET_PORTRAIT_4X4_GERMAN},

	{INPUT_MODE_4X4_TURKISH,		LYT_PORTRAIT_4X4_DEFAULT,			KEYSET_PORTRAIT_4X4_TURKISH},
	{INPUT_MODE_4X4_GREEK,			LYT_PORTRAIT_4X4_DEFAULT,			KEYSET_PORTRAIT_4X4_GREEK},
	{INPUT_MODE_4X4_RUSSIAN,		LYT_PORTRAIT_4X4_DEFAULT,			KEYSET_PORTRAIT_4X4_RUSSIAN},


	{INPUT_MODE_QTY_ENGLISH,		LYT_PORTRAIT_QTY_DEFAULT,			KEYSET_PORTRAIT_QTY_ENGLISH},
	{INPUT_MODE_QTY_URL,			LYT_PORTRAIT_QTY_URL,				KEYSET_PORTRAIT_QTY_URL},
	{INPUT_MODE_QTY_EMAIL,			LYT_PORTRAIT_QTY_EMAIL,				KEYSET_PORTRAIT_QTY_EMAIL},
	{INPUT_MODE_QTY_SYM_1,			LYT_PORTRAIT_QTY_DEFAULT,			KEYSET_PORTRAIT_QTY_SYM_1},
	{INPUT_MODE_QTY_SYM_2,			LYT_PORTRAIT_QTY_DEFAULT,			KEYSET_PORTRAIT_QTY_SYM_2},
	{INPUT_MODE_QTY_SYM_3,			LYT_PORTRAIT_QTY_DEFAULT,			KEYSET_PORTRAIT_QTY_SYM_3},
	{INPUT_MODE_QTY_SYM_4,			LYT_PORTRAIT_QTY_DEFAULT,			KEYSET_PORTRAIT_QTY_SYM_4},

	{INPUT_MODE_QTY_FRENCH,			LYT_PORTRAIT_AZT_DEFAULT,			KEYSET_PORTRAIT_QTY_FRENCH},
	{INPUT_MODE_QTY_SPANISH,		LYT_PORTRAIT_QTY_DEFAULT,			KEYSET_PORTRAIT_QTY_SPANISH},
	{INPUT_MODE_QTY_ITALIAN,		LYT_PORTRAIT_QTY_DEFAULT,			KEYSET_PORTRAIT_QTY_ITALIAN},
	{INPUT_MODE_QTY_DUTCH,			LYT_PORTRAIT_QTY_DEFAULT,			KEYSET_PORTRAIT_QTY_DUTCH},
	{INPUT_MODE_QTY_PORTUGUESE,		LYT_PORTRAIT_QTY_DEFAULT,			KEYSET_PORTRAIT_QTY_PORTUGUESE},
	{INPUT_MODE_QTY_GERMAN,			LYT_PORTRAIT_QTY_DEFAULT,			KEYSET_PORTRAIT_QTY_GERMAN},

	{INPUT_MODE_QTY_TURKISH,		LYT_PORTRAIT_QTY_DEFAULT,			KEYSET_PORTRAIT_QTY_TURKISH},
	{INPUT_MODE_QTY_GREEK,			LYT_PORTRAIT_QTY_DEFAULT,			KEYSET_PORTRAIT_QTY_GREEK},
	{INPUT_MODE_QTY_RUSSIAN,		LYT_PORTRAIT_QTY_RUSSIAN,			KEYSET_PORTRAIT_QTY_RUSSIAN},

	/*Landscape*/
	{INPUT_MODE_4X4_ENGLISH,		LYT_LANDSCAPE_QTY_DEFAULT,			KEYSET_LANDSCAPE_QTY_ENGLISH},

	{INPUT_MODE_4X4_FRENCH,			LYT_LANDSCAPE_QTY_DEFAULT,			KEYSET_LANDSCAPE_QTY_FRENCH},
	{INPUT_MODE_4X4_SPANISH,		LYT_LANDSCAPE_QTY_DEFAULT,			KEYSET_LANDSCAPE_QTY_SPANISH},
	{INPUT_MODE_4X4_ITALIAN,		LYT_LANDSCAPE_QTY_DEFAULT,			KEYSET_LANDSCAPE_QTY_ITALIAN},
	{INPUT_MODE_4X4_DUTCH,			LYT_LANDSCAPE_QTY_DEFAULT,			KEYSET_LANDSCAPE_QTY_DUTCH},
	{INPUT_MODE_4X4_PORTUGUESE,		LYT_LANDSCAPE_QTY_DEFAULT,			KEYSET_LANDSCAPE_QTY_PORTUGUESE},
	{INPUT_MODE_4X4_GERMAN,			LYT_LANDSCAPE_QTY_DEFAULT,			KEYSET_LANDSCAPE_QTY_GERMAN},

	{INPUT_MODE_4X4_TURKISH,		LYT_LANDSCAPE_QTY_DEFAULT,			KEYSET_LANDSCAPE_QTY_TURKISH},
	{INPUT_MODE_4X4_GREEK,			LYT_LANDSCAPE_QTY_DEFAULT,			KEYSET_LANDSCAPE_QTY_GREEK},
	{INPUT_MODE_4X4_RUSSIAN,		LYT_LANDSCAPE_QTY_RUSSIAN,			KEYSET_LANDSCAPE_QTY_RUSSIAN},

	{INPUT_MODE_4X4_NUM,			LYT_LANDSCAPE_4X4_NUM,				KEYSET_LANDSCAPE_4X4_NUM},
	{INPUT_MODE_4X4_TELEPHONE,		LYT_LANDSCAPE_4X4_NUM,				KEYSET_LANDSCAPE_4X4_NUM},

	{INPUT_MODE_4X4_SYM_1,			LYT_LANDSCAPE_QTY_DEFAULT,			KEYSET_PORTRAIT_QTY_SYM_1},
	{INPUT_MODE_4X4_SYM_2,			LYT_LANDSCAPE_QTY_DEFAULT,			KEYSET_PORTRAIT_QTY_SYM_1},
	{INPUT_MODE_4X4_SYM_3,			LYT_LANDSCAPE_QTY_DEFAULT,			KEYSET_PORTRAIT_QTY_SYM_1},
	{INPUT_MODE_4X4_SYM_4,			LYT_LANDSCAPE_QTY_DEFAULT,			KEYSET_PORTRAIT_QTY_SYM_1},
	{INPUT_MODE_4X4_SYM_5,			LYT_LANDSCAPE_QTY_DEFAULT,			KEYSET_PORTRAIT_QTY_SYM_1},

	{INPUT_MODE_4X4_URL,			LYT_LANDSCAPE_QTY_URL,				KEYSET_LANDSCAPE_QTY_URL},
	{INPUT_MODE_4X4_EMAIL,			LYT_LANDSCAPE_QTY_URL,				KEYSET_LANDSCAPE_QTY_EMAIL},
	{INPUT_MODE_4X4_PASSWD,			LYT_LANDSCAPE_4X4_PASSWD,			KEYSET_LANDSCAPE_4X4_PASSWD},
	{INPUT_MODE_4X4_IPv6_123,		LYT_LANDSCAPE_4X4_IPv6_123,			KEYSET_LANDSCAPE_4X4_IPv6_123},
	{INPUT_MODE_4X4_IPv6_ABC,		LYT_LANDSCAPE_4X4_IPv6_ABC,			KEYSET_LANDSCAPE_4X4_IPv6_ABC},
	{INPUT_MODE_4X4_NUMONLY,		LYT_LANDSCAPE_4X4_NUMONLY,			KEYSET_LANDSCAPE_4X4_NUMONLY},
	{INPUT_MODE_4X4_MONTH,			LYT_LANDSCAPE_4X4_NUM,				KEYSET_LANDSCAPE_4X4_MONTH},

	{INPUT_MODE_QTY_ENGLISH,		LYT_LANDSCAPE_QTY_DEFAULT,			KEYSET_LANDSCAPE_QTY_ENGLISH},
	{INPUT_MODE_QTY_URL,			LYT_LANDSCAPE_QTY_URL,				KEYSET_LANDSCAPE_QTY_URL},
	{INPUT_MODE_QTY_EMAIL,			LYT_LANDSCAPE_QTY_EMAIL,			KEYSET_LANDSCAPE_QTY_EMAIL},

	{INPUT_MODE_QTY_FRENCH,			LYT_LANDSCAPE_AZT_FRENCH,			KEYSET_LANDSCAPE_QTY_FRENCH},
	{INPUT_MODE_QTY_SPANISH,		LYT_LANDSCAPE_QTY_DEFAULT,			KEYSET_LANDSCAPE_QTY_SPANISH},
	{INPUT_MODE_QTY_ITALIAN,		LYT_LANDSCAPE_QTY_DEFAULT,			KEYSET_LANDSCAPE_QTY_ITALIAN},
	{INPUT_MODE_QTY_DUTCH,			LYT_LANDSCAPE_QTY_DEFAULT,			KEYSET_LANDSCAPE_QTY_DUTCH},
	{INPUT_MODE_QTY_PORTUGUESE,		LYT_LANDSCAPE_QTY_DEFAULT,			KEYSET_LANDSCAPE_QTY_PORTUGUESE},
	{INPUT_MODE_QTY_GERMAN,			LYT_LANDSCAPE_QTY_DEFAULT,			KEYSET_LANDSCAPE_QTY_GERMAN},

	{INPUT_MODE_QTY_TURKISH,		LYT_LANDSCAPE_QTY_DEFAULT,			KEYSET_LANDSCAPE_QTY_TURKISH},
	{INPUT_MODE_QTY_GREEK,			LYT_LANDSCAPE_QTY_DEFAULT,			KEYSET_LANDSCAPE_QTY_GREEK},
	{INPUT_MODE_QTY_RUSSIAN,		LYT_LANDSCAPE_QTY_RUSSIAN,			KEYSET_LANDSCAPE_QTY_RUSSIAN},


	{INPUT_MODE_QTY_SYM_1,			LYT_LANDSCAPE_QTY_DEFAULT,			KEYSET_PORTRAIT_QTY_SYM_1},
	{INPUT_MODE_QTY_SYM_2,			LYT_LANDSCAPE_QTY_DEFAULT,			KEYSET_PORTRAIT_QTY_SYM_2},
	{INPUT_MODE_QTY_SYM_3,			LYT_LANDSCAPE_QTY_DEFAULT,			KEYSET_PORTRAIT_QTY_SYM_3},
	{INPUT_MODE_QTY_SYM_4,			LYT_LANDSCAPE_QTY_DEFAULT,			KEYSET_PORTRAIT_QTY_SYM_4},

	/*Popup*/
	{INPUT_MODE_4X4_ENGLISH,		LYT_PORTRAIT_4X4_TEXTMODE_POPUP,	KEYSET_PORTRAIT_TEXTMODEPOPUP_4X4},

	{INPUT_MODE_4X4_NUM,			LYT_PORTRAIT_4X4_TEXTMODE_POPUP,	KEYSET_PORTRAIT_TEXTMODEPOPUP_4X4},

	{INPUT_MODE_4X4_FRENCH,			LYT_PORTRAIT_4X4_TEXTMODE_POPUP,	KEYSET_PORTRAIT_TEXTMODEPOPUP_4X4},
	{INPUT_MODE_4X4_SPANISH,		LYT_PORTRAIT_4X4_TEXTMODE_POPUP,	KEYSET_PORTRAIT_TEXTMODEPOPUP_4X4},
	{INPUT_MODE_4X4_ITALIAN,		LYT_PORTRAIT_4X4_TEXTMODE_POPUP,	KEYSET_PORTRAIT_TEXTMODEPOPUP_4X4},
	{INPUT_MODE_4X4_DUTCH,			LYT_PORTRAIT_4X4_TEXTMODE_POPUP,	KEYSET_PORTRAIT_TEXTMODEPOPUP_4X4},
	{INPUT_MODE_4X4_PORTUGUESE,		LYT_PORTRAIT_4X4_TEXTMODE_POPUP,	KEYSET_PORTRAIT_TEXTMODEPOPUP_4X4},
	{INPUT_MODE_4X4_GERMAN,			LYT_PORTRAIT_4X4_TEXTMODE_POPUP,	KEYSET_PORTRAIT_TEXTMODEPOPUP_4X4},

	{INPUT_MODE_4X4_TURKISH,		LYT_PORTRAIT_4X4_TEXTMODE_POPUP,	KEYSET_PORTRAIT_TEXTMODEPOPUP_4X4},
	{INPUT_MODE_4X4_GREEK,			LYT_PORTRAIT_4X4_TEXTMODE_POPUP,	KEYSET_PORTRAIT_TEXTMODEPOPUP_4X4},
	{INPUT_MODE_4X4_RUSSIAN,		LYT_PORTRAIT_4X4_TEXTMODE_POPUP,	KEYSET_PORTRAIT_TEXTMODEPOPUP_4X4},

	{INPUT_MODE_QTY_ENGLISH,		LYT_PUNCTUATION_POPUP,				KEYSET_PUNCTUATION_POPUP},
	{INPUT_MODE_QTY_FRENCH,		LYT_PUNCTUATION_POPUP,				KEYSET_PUNCTUATION_POPUP},
	{INPUT_MODE_QTY_SPANISH,		LYT_PUNCTUATION_POPUP,				KEYSET_PUNCTUATION_POPUP},
	{INPUT_MODE_QTY_ITALIAN,		LYT_PUNCTUATION_POPUP,				KEYSET_PUNCTUATION_POPUP},
	{INPUT_MODE_QTY_DUTCH,		LYT_PUNCTUATION_POPUP,				KEYSET_PUNCTUATION_POPUP},
	{INPUT_MODE_QTY_PORTUGUESE,		LYT_PUNCTUATION_POPUP,				KEYSET_PUNCTUATION_POPUP},
	{INPUT_MODE_QTY_GERMAN,		LYT_PUNCTUATION_POPUP,				KEYSET_PUNCTUATION_POPUP},
	{INPUT_MODE_QTY_TURKISH,		LYT_PUNCTUATION_POPUP,				KEYSET_PUNCTUATION_POPUP},
	{INPUT_MODE_QTY_GREEK,		LYT_PUNCTUATION_POPUP,				KEYSET_PUNCTUATION_POPUP},
	{INPUT_MODE_QTY_RUSSIAN,		LYT_PUNCTUATION_POPUP,				KEYSET_PUNCTUATION_POPUP},

	{INPUT_MODE_QTY_ENGLISH,		LYT_EMOTICON_POPUP,				KEYSET_EMOTICON_POPUP},
	{INPUT_MODE_QTY_FRENCH,			LYT_EMOTICON_POPUP,				KEYSET_EMOTICON_POPUP},
	{INPUT_MODE_QTY_SPANISH,		LYT_EMOTICON_POPUP,				KEYSET_EMOTICON_POPUP},
	{INPUT_MODE_QTY_ITALIAN,		LYT_EMOTICON_POPUP,				KEYSET_EMOTICON_POPUP},
	{INPUT_MODE_QTY_DUTCH,			LYT_EMOTICON_POPUP,				KEYSET_EMOTICON_POPUP},
	{INPUT_MODE_QTY_PORTUGUESE,		LYT_EMOTICON_POPUP,				KEYSET_EMOTICON_POPUP},
	{INPUT_MODE_QTY_GERMAN,			LYT_EMOTICON_POPUP,				KEYSET_EMOTICON_POPUP},
	{INPUT_MODE_QTY_TURKISH,		LYT_EMOTICON_POPUP,				KEYSET_EMOTICON_POPUP},
	{INPUT_MODE_QTY_GREEK,			LYT_EMOTICON_POPUP,				KEYSET_EMOTICON_POPUP},
	{INPUT_MODE_QTY_RUSSIAN,		LYT_EMOTICON_POPUP,				KEYSET_EMOTICON_POPUP},

	{INPUT_MODE_QTY_URL,			LYT_PUNCTUATION_POPUP,				KEYSET_PUNCTUATION_POPUP},
	{INPUT_MODE_QTY_EMAIL,			LYT_PUNCTUATION_POPUP,				KEYSET_PUNCTUATION_POPUP},
	{INPUT_MODE_QTY_SYM_1,			LYT_PUNCTUATION_POPUP,				KEYSET_PUNCTUATION_POPUP},
	{INPUT_MODE_QTY_SYM_2,			LYT_PUNCTUATION_POPUP,				KEYSET_PUNCTUATION_POPUP},
	{INPUT_MODE_QTY_SYM_3,			LYT_PUNCTUATION_POPUP,				KEYSET_PUNCTUATION_POPUP},
	{INPUT_MODE_QTY_SYM_4,			LYT_PUNCTUATION_POPUP,				KEYSET_PUNCTUATION_POPUP},

	{INPUT_MODE_QTY_URL,			LYT_EMOTICON_POPUP,				KEYSET_EMOTICON_POPUP},
	{INPUT_MODE_QTY_EMAIL,			LYT_EMOTICON_POPUP,				KEYSET_EMOTICON_POPUP},

	{INPUT_MODE_QTY_URL,			LYT_URL_POPUP,					KEYSET_URL_POPUP},
	{INPUT_MODE_QTY_EMAIL,			LYT_URL_POPUP,					KEYSET_URL_POPUP},
	{INPUT_MODE_QTY_ENGLISH,		LYT_URL_POPUP,					KEYSET_URL_POPUP},
	{INPUT_MODE_QTY_SYM_1,			LYT_URL_POPUP,					KEYSET_URL_POPUP},
	{INPUT_MODE_QTY_SYM_2,			LYT_URL_POPUP,					KEYSET_URL_POPUP},
	{INPUT_MODE_QTY_SYM_3,			LYT_URL_POPUP,					KEYSET_URL_POPUP},
	{INPUT_MODE_QTY_SYM_4,			LYT_URL_POPUP,					KEYSET_URL_POPUP},
	{INPUT_MODE_QTY_FRENCH,			LYT_URL_POPUP,					KEYSET_URL_POPUP},
	{INPUT_MODE_QTY_SPANISH,		LYT_URL_POPUP,					KEYSET_URL_POPUP},
	{INPUT_MODE_QTY_ITALIAN,		LYT_URL_POPUP,					KEYSET_URL_POPUP},
	{INPUT_MODE_QTY_DUTCH,			LYT_URL_POPUP,					KEYSET_URL_POPUP},
	{INPUT_MODE_QTY_PORTUGUESE,		LYT_URL_POPUP,					KEYSET_URL_POPUP},
	{INPUT_MODE_QTY_GERMAN,			LYT_URL_POPUP,					KEYSET_URL_POPUP},
	{INPUT_MODE_QTY_TURKISH,		LYT_URL_POPUP,					KEYSET_URL_POPUP},
	{INPUT_MODE_QTY_GREEK,			LYT_URL_POPUP,					KEYSET_URL_POPUP},
	{INPUT_MODE_QTY_RUSSIAN,		LYT_URL_POPUP,					KEYSET_URL_POPUP},

};


static McfSWButtonStyle mcf_swbutton_style[] = {
	{
		{5, 5},
		{{255, 255, 255},{255, 255, 255}},
		{{155, 155, 155},{255, 0, 0}},
		0,
		1.0
	},
};

typedef enum _McfSWButtonStyleSet {
	SW_BTN_STYLE_A,
}McfSWButtonStyleSet;

const McfDefaultConfigure mcf_default_configure = {
	MCFDISPLAY_PORTRAIT,
	INPUT_MODE_QTY_ENGLISH,
	TRUE,
	TRUE,
	TRUE,
	TRUE,
	FALSE,
	SW_BTN_STYLE_A,
	{TOUCH_OFFSET_LEVEL_1,TOUCH_OFFSET_LEVEL_2},
#if defined(__arm__)
	{{0, -20},{0, -15}}
#else
	{{0, 0},{0, 0}}
#endif
};

static McfLabelProperties CAND_LABEL_PROP = {
	USED, DEFAULT_FONT_NAME, DEFAULT_FONT_SIZE, {{0 , 0, 0, 255}, {0, 0, 255, 255}}, LABEL_ALIGN_CENTER_MIDDLE
};

static McfLabelProperties ZOOMING_LABEL_PROP = {
	USED, DEFAULT_FONT_NAME, 80, {{0 , 0, 0, 255}, {0, 0, 255, 255}}, LABEL_ALIGN_CENTER_MIDDLE
};

static McfLabelProperties AUTOPOPUP_LABEL_PROP = {
	USED, DEFAULT_FONT_NAME, 54,     {
			{{255, 255, 255, 255}, COLOR_SHIFT_STATE_COLOR},
			{COLOR_SHIFT_STATE_COLOR, { 255, 255, 255, 255}},
			{COLOR_SHIFT_STATE_COLOR, { 255, 255, 255, 255}},
	}, LABEL_ALIGN_CENTER_MIDDLE, 0, 0
 };

extern McfAutoPopupConfigure mcf_autopopup_configure;
extern McfDimWndConfigure mcf_dim_window_configure;

static const McfNinePatchInfo mcf_nine_patch_info[] = {
	{"textinput_moa_button1_nml.png", 3, 3, 3, 3},
	{"textinput_moa_button1_function.png", 3, 3, 3, 3},
	{"textinput_moa_button1_press.png", 3, 3, 3, 3},
	{"textinput_moa_button1_press_drag.png", 3, 3, 3, 3},
	{"textinput_moa_button1_press_drag_back.png", 3, 3, 3, 3},
	{"textinput_moa_button1_press_drag_back_Diagonal.png", 3, 3, 3, 3},
	{"textinput_moa_button2_nml.png", 3, 3, 3, 3},
	{"textinput_moa_button2_press.png", 3, 3, 3, 3},
	{"textinput_moa_button2_press_drag.png", 3, 3, 3, 3},
	{"textinput_moa_button2_press_drag_back.png", 3, 3, 3, 3},
	{"textinput_qwerty_button_nml.png", 3, 3, 3, 3},
	{"textinput_qwerty_button_function.png", 3, 3, 3, 3},
	{"textinput_qwerty_button_press.png", 3, 3, 3, 3},
	{"textinput_qwerty_button_capslock_press.png", 3, 3, 3, 3},
	{"textinput_bottom_button_nml.png", 3, 3, 3, 3},
	{"textinput_bottom_button_function.png", 3, 3, 3, 3},
	{"textinput_bottom_button_press.png", 3, 3, 3, 3},
	{"textinput_popup_button_nml.png", 3, 3, 3, 3},
	{"textinput_popup_button_press.png", 3, 3, 3, 3},
	{"textinput_3x4_button_nml.png", 3, 3, 3, 3},
	{"textinput_3x4_button_function.png", 3, 3, 3, 3},
	{"textinput_3x4_button_press.png", 3, 3, 3, 3},
	{"textinput_land_button_nml.png", 3, 3, 3, 3},
	{"textinput_land_button_function.png", 3, 3, 3, 3},
	{"textinput_land_button_press.png", 3, 3, 3, 3},
	{"textinput_land_button_capslock_press.png", 3, 3, 3, 3},
	{"textinput_land_button_press_drag.png", 3, 3, 3, 3},
	{"textinput_land_button_press_drag_back.png", 3, 3, 3, 3},
	{"B09_bg_Popup.png", 13, 13, 9, 9},
	{"B09_bubble_bg.png", 7, 7, 9, 9},
	{"B09_key_btn_01.png", 8, 8, 0, 0},
	{"B09_key_btn_02.png",  8, 8, 0, 0},
	{"B09_key_btn_press.png",  8, 8, 0, 0},
	{"B09_Qwerty_btn_01.png", 8, 8, 0, 0},
	{"B09_Qwerty_btn_02.png", 8, 8, 0, 0},
	{"B09_Qwerty_btn_press.png", 8, 8, 0, 0},
	{"B09_Qwerty_l_btn_01.png", 8, 8, 0, 0},
	{"B09_Qwerty_l_btn_02.png", 8, 8, 0, 0},
	{"B09_Qwerty_l_btn_press.png", 8, 8, 0, 0},
};

typedef enum _MCFModifierDecoration {
	MODIFIER_DECORATION_NONE = 0, // The 0 value decoration will never be drawn
	MODIFIER_DECORATION_NUM
}MCFModifierDecoration;

extern McfModifierDecoration mcf_modifier_decoration[MODIFIER_DECORATION_NUM];

const mcfdouble DEFAULT_SW_BTN_RECTANGLE_RADIUS = 10;


//MCF_END_DECLS
#endif
